version: 2

models:
  - name: date_dim
    description: "Calendar date dimension"
    columns:
      - name: date
        description: "Calendar date"
        tests:
          - not_null
          - unique
      - name: year
        description: "Year component"
      - name: month
        description: "Month component (1-12)"
      - name: day
        description: "Day component (1-31)"
      - name: weekday
        description: "Day of week (1=Sunday, 7=Saturday)"

  - name: dim_stock
    description: "Stock master dimension"
    columns:
      - name: symbol
        description: "Stock ticker symbol"
        tests:
          - not_null
          - unique
      - name: sector
        description: "Sector classification from test fundamentals"
