name: Airflow DAG Validation
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  validate-dags:
    name: Validate Airflow DAGs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install Airflow
        run: |
          python -m pip install --upgrade pip
          pip install apache-airflow apache-airflow-providers-google
      - name: List DAGs
        run: |
          export AIRFLOW_HOME=${{ github.workspace }}/airflow
          airflow db init
          airflow dags list