name: Lint
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    name: Black & Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8
      - name: Run Black
        run: black --check .
      - name: Run Flake8
        run: flake8