version: 2

models:
  # Staging models for streaming and static sources
  - name: stg_streaming_stock_data
    description: "Staged intraday stock data from streaming pipeline"
    columns:
      - name: symbol
        description: "Stock ticker symbol"
        tests:
          - not_null
      - name: timestamp
        description: "Timestamp of the intraday quote"
        tests:
          - not_null
      - name: open
        description: "Opening price"
      - name: high
        description: "High price"
      - name: low
        description: "Low price"
      - name: close
        description: "Closing price"
      - name: volume
        description: "Volume traded"

  - name: stg_sandp500_data
    description: "Staged S&P 500 daily index data"
    columns:
      - name: date
        description: "Date of the index record"
        tests:
          - not_null
      - name: open
        description: "Opening index value"
      - name: high
      - name: low
      - name: close
      - name: volume

  - name: stg_crypto_price_history
    description: "Staged cryptocurrency price history data"
    columns:
      - name: date
        description: "Date of the record"
        tests:
          - not_null
      - name: symbol
        description: "Cryptocurrency symbol"
        tests:
          - not_null
      - name: open
      - name: high
      - name: low
      - name: close
      - name: volume

  - name: stg_global_economy_indicators
    description: "Staged global economy indicators data"
    columns:
      - name: country
        description: "Country name"
      - name: indicator
        description: "Indicator name"
      - name: year
        description: "Year"
      - name: value
        description: "Indicator value"

  - name: stg_realtime_mock_stock_data
    description: "Staged mock real-time stock data from the mock pipeline"
    columns:
      - name: symbol
        description: "Stock ticker symbol"
        tests:
          - not_null
      - name: timestamp
        description: "Timestamp of the mock data point"
        tests:
          - not_null
      - name: date
        description: "Date component of the timestamp"
        tests:
          - not_null
      - name: time
        description: "Time component of the timestamp"
        tests:
          - not_null
      - name: open
        description: "Opening price"
      - name: high
        description: "High price"
      - name: low
        description: "Low price"
      - name: close
        description: "Closing price"
      - name: volume
        description: "Volume traded"

  - name: int_daily_stock_summary
    description: "Daily OHLCV summary for each mock real-time stock symbol"
    tests:
      - unique_combination_of:
          combination_of: [symbol, date]
    columns:
      - name: symbol
        description: "Stock symbol"
        tests:
          - not_null
      - name: date
        description: "Date of the summary"
        tests:
          - not_null
      - name: open
        description: "Opening price of the day"
      - name: high
        description: "Highest price of the day"
      - name: low
        description: "Lowest price of the day"
      - name: close
        description: "Closing price of the day"
      - name: volume
        description: "Total volume traded in the day"
  # Marts: final fact table
  - name: daily_stock_signals
    description: "Final fact table combining daily stock OHLCV with market and macro indicators"
    columns:
      - name: symbol
        description: "Stock symbol"
        tests:
          - not_null
      - name: date
        description: "Date of the record"
        tests:
          - not_null
      - name: open
        description: "Opening price"
      - name: high
        description: "High price"
      - name: low
        description: "Low price"
      - name: close
        description: "Closing price"
      - name: volume
        description: "Total volume traded"
      - name: sp500_close
        description: "S&P 500 closing value"
      - name: crypto_avg_close
        description: "Average closing value across cryptocurrencies"
      - name: gdp_per_capita
        description: "GDP per capita for United States (filtered indicator)"